sudo: required
language: cpp
compiler:
    - clang
before_install:
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make install
install:
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  - ls /usr/local
  - ls /usr/bin
  - ls /usr/clang
  - ls /usr/clang-3.4
  - export CLANG_PATH_TO_LLVM_BUILD="/usr/local/bin"
